### ISSUE TITLE
Condense all projects to a single repository

### ISSUE THREAD

**Issue by cnishina** [testing-angular-applications/testing-angular-applications#24]
Stage all changes to a migration branch

- [x] Move contacts app starter to a `website/` folder
- [x] Rebase this repository with chapter repositories to maintain git history. Should maintain any circle ci or travis tests and roll them into the same test
- [x] Change the repository name to test-angular-applications
- [ ] Rebase experiment branch?

**Comment by jesselpalmer** [comment]
@cnishina can this be closed?

**Comment by cnishina** [comment]
I will move the experiment to either be at a separate repository or a rebased branch.

**Comment by jesselpalmer** [comment]
cool
