### ISSUE TITLE
warnings  at windows 10  platform run "npm install" 

### ISSUE THREAD

**Issue by mingqin1** [testing-angular-applications/testing-angular-applications#69]
Authors:
My environments: windows 10 ; node version v8.9.3; npm version 5.5.1
The code based is master branch.
when I run "npm install"  I got following warning.
C:\openSourceProjects\testing-angular-applications-master\website>npm install
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@6.0.6 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 115 packages in 20.285s

**Comment by jesselpalmer** [comment]
Closing since this seems to be related to #72
