### ISSUE TITLE
failed on run unit test against contact-edit.component.spec.ts in windows 10, master branch

### ISSUE THREAD

**Issue by mingqin1** [testing-angular-applications/testing-angular-applications#72]
Authors:

My environments: windows 10 ; node version v8.9.3; npm version 5.5.1
The code based is master branch. After copying and pasting contact-edit-component.spec.ts from chapter03 folder to website/src/app/contacts/contact-edit

when I run "ng test" I got following errors

C:\openSourceProjects\testing-angular-applications-master\website>ng test
Your global Angular CLI version (1.7.3) is greater than your local
version (1.6.8). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
 10% building modules 1/1 modules 0 active09 04 2018 19:28:54.041:WARN [karma]: No captured browser, open http://localhost:9876/
09 04 2018 19:28:54.072:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
09 04 2018 19:28:54.075:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 04 2018 19:28:54.092:INFO [launcher]: Starting browser Chrome                                                                                                      [../../../../../src recursive \.spec\.ts$] ./src \.spec\.ts$ 261 bytes {main} [built]
[../../../../../src/polyfills.ts] ./src/polyfills.ts 2.6 kB {polyfills} [built]
[../../../../../src/test.ts] ./src/test.ts 1.01 kB {main} [built]
[../../../../zone.js/dist/async-test.js] ./node_modules/zone.js/dist/async-test.js 3.23 kB {vendor} [built]
[../../../../zone.js/dist/fake-async-test.js] ./node_modules/zone.js/dist/fake-async-test.js 17 kB {vendor} [built]
[../../../../zone.js/dist/jasmine-patch.js] ./node_modules/zone.js/dist/jasmine-patch.js 6.36 kB {vendor} [built]
[../../../../zone.js/dist/long-stack-trace-zone.js] ./node_modules/zone.js/dist/long-stack-trace-zone.js 6.22 kB {vendor} [built]
[../../../../zone.js/dist/proxy.js] ./node_modules/zone.js/dist/proxy.js 5.6 kB {vendor} [built]
[../../../../zone.js/dist/sync-test.js] ./node_modules/zone.js/dist/sync-test.js 1.41 kB {vendor} [built]
[../../../../zone.js/dist/zone.js] ./node_modules/zone.js/dist/zone.js 126 kB {polyfills} [built]
[../../../compiler/esm5/compiler.js] ./node_modules/@angular/compiler/esm5/compiler.js 1.2 MB {vendor} [built]
   [0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[../../../core/esm5/testing.js] ./node_modules/@angular/core/esm5/testing.js 49.9 kB {vendor} [built]
[../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js] ./node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js 24.9 kB {vendor} [built]
[../../../platform-browser-dynamic/esm5/testing.js] ./node_modules/@angular/platform-browser-dynamic/esm5/testing.js 17.9 kB {vendor} [built]
    + 282 hidden modules

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/material-app-theme.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/material-app-theme.scss 4:14-203
 @ ./src/app/contacts/contact-edit/contacts-edit.component.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
09 04 2018 19:29:54.095:WARN [launcher]: Chrome have not captured in 60000 ms, killing.

**Comment by jesselpalmer** [comment]
Looks like `node-sass` isn't building properly. Could you try to go through the steps here and see if that helps: https://github.com/sass/node-sass/issues/1991

**Comment by cnishina** [comment]
Also, instead of trying to run with a global version mismatch on the angular cli, would it make sense to run the version set from the [package.json](https://github.com/testing-angular-applications/testing-angular-applications/blob/master/website/package.json#L10)? `npm run ng test`

**Comment by jesselpalmer** [comment]
@mingqin1 Could you let us know if you still are having this issue as well as #71 and #69? Otherwise, I'm going to close these if I do not hear from you. Thank you!

**Comment by mingqin1** [comment]
Please close this issue

**Comment by jesselpalmer** [comment]
Thank you!
